import { initializeApp, getApps, getApp } from 'firebase/app';
import { getAuth, GoogleAuthProvider } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

// Safely attempt to load firebase-applet-config.json if generated by set_up_firebase tool
const appletConfigs = import.meta.glob('/firebase-applet-config.json', { eager: true });
const appletConfig = ((appletConfigs['/firebase-applet-config.json'] as any)?.default ||
  appletConfigs['/firebase-applet-config.json']) as Record<string, string> | undefined;

const apiKey = appletConfig?.apiKey || import.meta.env.VITE_FIREBASE_API_KEY || '';
const authDomain = appletConfig?.authDomain || import.meta.env.VITE_FIREBASE_AUTH_DOMAIN || '';
const projectId = appletConfig?.projectId || import.meta.env.VITE_FIREBASE_PROJECT_ID || '';
const storageBucket = appletConfig?.storageBucket || import.meta.env.VITE_FIREBASE_STORAGE_BUCKET || '';
const messagingSenderId = appletConfig?.messagingSenderId || import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID || '';
const appId = appletConfig?.appId || import.meta.env.VITE_FIREBASE_APP_ID || '';
const firestoreDatabaseId = appletConfig?.firestoreDatabaseId || import.meta.env.VITE_FIREBASE_DATABASE_ID || undefined;

// Firebase web configuration
const firebaseConfig = {
  apiKey,
  authDomain,
  projectId,
  storageBucket,
  messagingSenderId,
  appId,
};

// Check for missing or dummy API key
const isInvalidKey =
  !apiKey ||
  apiKey.includes('sample-key') ||
  apiKey === 'YOUR_API_KEY' ||
  apiKey.trim() === '';

if (isInvalidKey) {
  console.error(
    '[Firebase Configuration Alert] Firebase API key is missing or invalid. ' +
    'Please configure VITE_FIREBASE_* environment variables or run Firebase setup.'
  );
}

// Initialize Firebase App safely
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();

export const auth = getAuth(app);
export const db = firestoreDatabaseId ? getFirestore(app, firestoreDatabaseId) : getFirestore(app);

export const googleProvider = new GoogleAuthProvider();
googleProvider.setCustomParameters({ prompt: 'select_account' });

